name = "github2gchat-webhook"
main = "src/index.js"
compatibility_date = "2022-07-18"

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
  binding = "KV"
  id = "eaf16a1ca529448daf5ca1081bab0b96"
  preview_id = "652cc496fb8d4d9f8b5b7a053ef6dc94"